authapp/urls.py
from django.conf.urls import url

import authapp.views as authapp

app_name = 'auth'
urlpatterns = [
    url(r'^login/$', authapp.login, name='login'),
    url(r'^logout/$', authapp.logout, name='logout'),
    url(r'^register/$', authapp.register, name='register'),
    url(r'^edit/$', authapp.edit, name='edit'),
]

basketapp/urls.py
from django.urls import path, re_path
from . import views
import basketapp.views as basketapp

app_name = 'basket'

urlpatterns = [
    path(r'^$', basketapp.basket, name='view'),
    path('add/<int:pk>/', basketapp.basket_add, name='add'),
    path('remove/<int:pk>/', basketapp.basket_remove, name='remove'),
]

contactsapp/urls.py
from django.urls import path, re_path
from . import views

app_name = 'contacts'
urlpatterns = [
    re_path(r'^$', views.main, name='main'),
]

geekbrains/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^$', include('mainapp.urls')),
    path('catalog/', include('productsapp.urls')),
    path('contact/', include('contactsapp.urls')),
    path(r'^basket/', include('basketapp.urls')),
    re_path(r'^auth/', include('authapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

productsapp/urls.py
from django.urls import path, re_path
from productsapp.views import (main, ProductDetailView, ProductCreateView, ProductDeleteView, ProductUpdateView,
                               ProductListView, CategoryUpdateView, CategoryCreateView, CategoryDeleteView)

app_name = 'products'

urlpatterns = [
    re_path(r'^$', ProductListView.as_view(), name='catalog'),
    path('<int:good_id>/', ProductDetailView.as_view(), name='detail'),
    path('create_prod/', ProductCreateView.as_view(), name='create_prod'),
    path('update_prod/<int:pk>/', ProductUpdateView.as_view(), name='update_prod'),
    path('delete_prod/<int:pk>/', ProductDeleteView.as_view(), name='delete_prod'),

    path('create_cat/', CategoryCreateView.as_view(), name='create_cat'),
    path('update_cat/<int:pk>/', CategoryUpdateView.as_view(), name='update_cat'),
    path('delete_cat/<int:pk>/', CategoryDeleteView.as_view(), name='delete_cat'),
]

productsapp/models.py
from django.db import models
from django.utils import timezone
from authapp.models import ShopUser


def user_directory_path(instance, filename):
    print(instance)
    return 'static/images/goods/{}'.format(filename)


class Photo(models.Model):
    # good = models.ForeignKey(Good, on_delete=models.CASCADE, related_name="photos", related_query_name="photo", )
    title = models.CharField(max_length=200, blank=True)
    alt = models.CharField(max_length=255, blank=True)
    src = models.ImageField(upload_to=user_directory_path)

    def __str__(self):
        return '{} - {}'.format(self.pk, self.src.name)


class ProductCategory(models.Model):
    name = models.CharField(verbose_name='имя', max_length=64, unique=True)
    description = models.TextField(verbose_name='описание', blank=True)

    def __str__(self):
        return self.name


class Good(models.Model):
    author = models.ForeignKey(ShopUser, on_delete=models.CASCADE)
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    photos = models.ManyToManyField(Photo)

    short_desc = models.CharField(max_length=255)
    description = models.TextField()
    price = models.DecimalField(max_digits=8, decimal_places=2, default=0)

    created_date = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.name

productsapp/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _

from productsapp.models import (
    ProductCategory, Good
)


class ProductCategoryModelForm(forms.ModelForm):
    class Meta:
        model = ProductCategory
        fields = ['name', 'description']
        labels = {
            'name': _('Название'),
            'description': _('Описание'),
        }


class GoodModelForm(forms.ModelForm):
    class Meta:
        model = Good
        fields = [
            'category', 'name', 'photos', 'short_desc', 'description', 'price'
        ]

productsapp/views/categories.py
from django.urls import reverse_lazy

from productsapp.models import ProductCategory
from productsapp.forms import (ProductCategoryModelForm)
from django.views.generic import (CreateView, UpdateView, DeleteView)


class CategoryCreateView(CreateView):
    model = ProductCategory
    template_name = 'productsapp/catalog_crud.html'
    form_class = ProductCategoryModelForm
    success_url = reverse_lazy('products:catalog')

    def get_context_data(self, **kwargs):
        context = super(CategoryCreateView, self).get_context_data(**kwargs)
        context['h1'] = 'Добавление категории'
        context['h2'] = 'Добавить категорию'

        return context


class CategoryUpdateView(UpdateView):
    model = ProductCategory
    template_name = 'productsapp/catalog_crud.html'
    form_class = ProductCategoryModelForm
    success_url = reverse_lazy('products:catalog')

    def get_context_data(self, **kwargs):
        context = super(CategoryUpdateView, self).get_context_data(**kwargs)
        context['h1'] = 'Обновление категории'
        context['h2'] = 'Обновить категорию'

        return context


class CategoryDeleteView(DeleteView):
    model = ProductCategory
    template_name = 'productsapp/catalog_crud.html'
    success_url = reverse_lazy('products:catalog')

    def get_context_data(self, **kwargs):
        context = super(CategoryDeleteView, self).get_context_data(**kwargs)
        context['h1'] = 'Удаление категории'
        context['h2'] = 'Удалить категорию'

        return context

productsapp/views/products.py
import json
import os

from django.utils import timezone
from django.conf import settings
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.template import loader
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.urls import reverse_lazy

from django.views.generic import (
    ListView, DetailView, CreateView, UpdateView, DeleteView)

from productsapp.models import Good, ProductCategory
from productsapp.forms import (GoodModelForm, ProductCategoryModelForm)


class ProductListView(ListView):
    model = Good
    template_name = 'productsapp/ext_catalog.html'
    context_object_name = 'goods'
    paginate_by = 6
    cat_id = None

    def get_queryset(self):
        self.cat_id = self.request.GET.get('cat', '')
        if self.cat_id:
            self.goods = Good.objects.filter(category=self.cat_id)
        else:
            self.goods = Good.objects.all()
        return self.goods

    def get_context_data(self, **kwargs):
        context = super(ProductListView, self).get_context_data(**kwargs)
        cats = ProductCategory.objects.all()
        context['categorys'] = cats
        if self.cat_id:
            context['cat_id'] = self.cat_id

        return context


def main(request):
    cat_id = request.GET.get('cat', '')
    if cat_id:
        goods = Good.objects.filter(category=cat_id)
    else:
        goods = Good.objects.all()

    cats = ProductCategory.objects.all()

    # print(request, request.is_ajax())

    if request.method == 'POST' and request.is_ajax():
        id = request.POST.get('id')
        if id:
            goods = goods.filter(category=id)

            paginator = Paginator(goods, 6)

            page = request.POST.get('page')

            try:
                goods = paginator.page(page)
            except PageNotAnInteger:
                goods = paginator.page(1)
            except EmptyPage:
                goods = paginator.page(paginator.num_pages)

            # data = serializers.serialize('json', goods)
            # return HttpResponse(data, content_type="application/json")

            goods_html = loader.render_to_string('productsapp/inc_goods.html', {'goods': goods}
                                                 )
            output_data = {'goods_html': goods_html, 'cat_id': id}

            return JsonResponse(output_data)
    else:
        paginator = Paginator(goods, 6)

        page = request.GET.get('page')

        try:
            goods = paginator.page(page)
        except PageNotAnInteger:
            goods = paginator.page(1)
        except EmptyPage:
            goods = paginator.page(paginator.num_pages)

        context = {}
        context['goods'] = goods
        context['categorys'] = cats
        if cat_id:
            context['cat_id'] = cat_id

        return render(request, 'productsapp/ext_catalog.html', context=context)


class ProductDetailView(DetailView):
    model = Good
    template_name = 'productsapp/good.html'
    context_object_name = 'good'
    pk_url_kwarg = 'good_id'

    def get_context_data(self, **kwargs):
        context = super(ProductDetailView, self).get_context_data(**kwargs)

        characteristic = {}
        static_path = settings.STATICFILES_DIRS[0]

        # Загрузка характеристик из файла.
        with open(os.path.join(static_path, 'data.json'), encoding='utf-8') as f:
            characteristics = json.load(f)
        if characteristics and self.kwargs['good_id'] < len(characteristics):
            characteristic = characteristics[self.kwargs['good_id'] - 1]

        context['characteristics'] = characteristic

        return context


class ProductCreateView(CreateView):
    model = Good
    template_name = 'productsapp/catalog_crud.html'
    context_object_name = 'form'
    form_class = GoodModelForm
    success_url = reverse_lazy('products:catalog')

    def form_valid(self, form):
        current_user = self.request.user
        if not current_user.is_anonymous:
            form.instance.author = current_user
            form.instance.published_date = timezone.now()
        return super(ProductCreateView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(ProductCreateView, self).get_context_data(**kwargs)
        context['h1'] = 'Добавление товара'
        context['h2'] = 'Добавить товар'

        return context


class ProductUpdateView(UpdateView):
    model = Good
    template_name = 'productsapp/catalog_crud.html'
    form_class = GoodModelForm
    success_url = reverse_lazy('products:catalog')

    def get_context_data(self, **kwargs):
        context = super(ProductUpdateView, self).get_context_data(**kwargs)
        context['h1'] = 'Обновление товара'
        context['h2'] = 'Обновить товар'

        return context


class ProductDeleteView(DeleteView):
    model = Good
    template_name = 'productsapp/catalog_crud.html'
    success_url = reverse_lazy('products:catalog')

    def get_context_data(self, **kwargs):
        context = super(ProductDeleteView, self).get_context_data(**kwargs)
        context['h1'] = 'Удаление товара'
        context['h2'] = 'Удалить товар'

        return context

productsapp/templates/productsapp/catalog.html
{% include "head.html" %}
<body>
<div class="outer">
    <header id="menu">
        {% include "menu.html" %}
    </header>
    <section id="main">
        <div class="mainWrap">
            <div class="contentLeft">
                <div class="mainMenu">
                    <a href="/">Главная</a>
                    <a href="/catalog">Каталог</a>
                    {% for cat in cats %}
                    <a class="categoryMenu" href="javascript:" onclick="get_ajax({{cat.pk}})">{{ cat.name }}</a>
                    {% endfor %}
                    <a href="/contact">Контакты</a>
                </div>
            </div>
            <div class="contentRight">
                <div class="contentHeader">
                    <h1>Каталог</h1>
                </div>
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Главная</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Каталог</li>
                    </ol>
                </nav>
                <div class="catalog_goods">
                    {% include 'productsapp/goods.html' %}
                </div>
            </div>
        </div>
    </section>
    <footer id="footer">
        {% include "footer.html" %}
    </footer>
</div>
<script>
function get_ajax(id)
{
$.ajax({
    url: '/catalog/',
    headers: {'X-CSRFToken': '{{ csrf_token }}'},
    type: "POST",
    data: {'id':id},
    cache:false,
    dataType: "json",
    success: function(resp){
        $('.catalog_goods').html(resp.goods_html);
    }
});
}
</script>
</body>
</html>

productsapp/templates/productsapp/catalog_crud.html
{% extends 'mainapp/base_tmp.html' %}
{% block carousel %}
{% endblock %}

{% block breadcrumb %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/">Главная</a></li>
        <li class="breadcrumb-item active" aria-current="page">Каталог</li>
    </ol>
</nav>
{% endblock %}
{% block left %}
{% endblock %}
{% block content %}
<h1 class="my-4">{{ h1 }}</h1>
<div class="container">
    <div class="row">
        <div class="col-lg-12 col-md-12">
            <h2>{{ h2 }}</h2>
            <form data-toggle="validator" role="form" method="POST" class="post-form">{% csrf_token %}
                <div class="controls">
                    <div class="row">
                        {% for field in form %}
                        <div class="form-group">
                            {{ field.errors }}
                            {{ field.label_tag }}
                            {{ field }}
                        </div>
                        {% endfor %}
                        <div class="col-md-12">
                            <input type="submit" class="btn btn-success btn-send" value="Отправить">
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <p class="text-muted">
                                    <strong>*</strong> Обязательные поля.
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

productsapp/templates/productsapp/ext_catalog.html
{% extends 'mainapp/base_tmp.html' %}
{% block carousel %}
{% endblock %}
{% block categorys %}
<div class='list-group'>
    {% for cat in categorys %}
    <!--<a class='list-group-item' href='javascript:' onclick='get_ajax({{cat.pk}})'>{{ cat.name }}</a>-->
    <a class="list-group-item" href="{% url 'products:catalog' %}?cat={{cat.pk}}">{{ cat.name }}</a>
    {% endfor %}
</div>
<br>
{% if user.is_authenticated %}
<div class='list-group'>
    {% if cat_id %}
    <a class="list-group-item" href="{% url 'products:update_cat' cat_id %}">Изменить категорию</a>
    <a class="list-group-item" href="{% url 'products:delete_cat' cat_id %}">Удалить категорию</a>
    {% else %}
    <a class="list-group-item" href="{% url 'products:create_cat' %}">Добавить категорию</a>
    {% endif %}
</div>
<br>
<div class='list-group'>
    <a class="list-group-item" href="{% url 'products:create_prod' %}">Добавить товар</a>
</div>
{% endif %}
{% endblock %}
{% block content %}
<h1 class='my-4'>Каталог товаров</h1>
<div id='loader' class='nodisp'></div>
<div id='catalog_goods' class='row'>
    {% include 'productsapp/inc_goods.html' %}
</div>
{% endblock %}
{% block pagination%}
<div class="row justify-content-center">
    <nav aria-label="Страницы:">
        <ul class="pagination">
            {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}&cat={{ cat_id }}">Назад</a>
            </li>
            {% endif %}
            <li class="page-item">
                <span class="page-link">Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}</span>
            </li>
            {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link"
                                     href="?page={{ page_obj.next_page_number }}&cat={{ cat_id }}">Вперед</a></li>
            {% endif %}
        </ul>
    </nav>
</div>
{% endblock %}
{% block script %}
{{ block.super }}
<script>
function get_ajax(id)
{
$('#loader').removeClass('nodisp');
$('#catalog_goods').addClass('nodisp');

$.ajax({
    url: '/catalog/?cat='+id,
    headers: {'X-CSRFToken': '{{ csrf_token }}'},
    type: 'POST',
    data: {'id':id},
    cache:false,
    dataType: 'json',
    success: function(resp){
        $('#catalog_goods').html(resp.goods_html);
        console.log(resp.cat_id);

        $('#loader').addClass('nodisp');
        $('#catalog_goods').removeClass('nodisp');

        window.history.pushState({"html":resp.goods_html},"", "{% url 'products:catalog' %}?cat="+id);
    }
});
}

$(window).on('load', function(){
    window.history.replaceState({"html":$('#catalog_goods').html()},"", "");
});

window.onpopstate = function(e){
    if(e.state){
        $('#catalog_goods').html(e.state.html);
    }
};





</script>
{% endblock %}

productsapp/templates/productsapp/good.html
<!DOCTYPE html>
<html lang="en">
{% load util %}
{% load staticfiles %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Django Framework. Часть 1. Сандал А. Я.</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css"
          integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{%  static '/css/shop-homepage.css' %}">
    <link rel="stylesheet" type="text/css" href="{%  static '/css/gallery.css' %}">
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="/">Главная</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'products:catalog' %}">Каталог</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'contacts:main' %}">Контакты</a>
                </li>
            </ul>
            <ul class="navbar-nav  ml-auto">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auth:edit' %}">{% if user.first_name > '' %}{{ user.first_name
                        }}{% else %}{{ user.username }}{% endif %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auth:logout' %}">Выйти</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="#" data-toggle="modal" data-target="#LoginPopup">Логин</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<div class="container">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href=".">Главная</a></li>
            <li class="breadcrumb-item"><a href="{% url 'products:catalog' %}">Каталог</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{good.name}}</li>
        </ol>
    </nav>
    {% if user.is_authenticated %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCRUD"
                    aria-controls="navbarCRUD" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCRUD">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'products:update_prod' good.pk %}">Изменить товар</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'products:delete_prod' good.pk %}">Удалить товар</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    {% endif %}
    {% for message in messages %}
    <div class="alert {{ message.tags }} alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Закрыть">
            <span aria-hidden="true">&times;</span>
        </button>
        {{ message }}
    </div>
    {% endfor %}
    <div class="row justify-content-center">
        <div class="col-lg-9">
            <h1 class="my-4">{{ good.name }}</h1>
            {% include 'productsapp/slider.html' %}
            <h2>Описание:</h2>
            <div id="brief">
                <p>Описание товара {{good.name}}</p>
                <p>
                    {{ good.short_desc}}
                </p>
            </div>
            <div class="productPriceWrap">
                <div class="actualPrice">
                    &euro; {{good.price}}
                </div>
            </div>
            <div id="cart">
                <a href="{% url 'basket:add' good.pk %}" class="btn btn-success btn-send">В корзину!</a>
            </div>
            <h2 class="clear">Характеристики товара:</h2>
            <ol class="good_descr">
                {% for mykey,myvalue in characteristics.items %}
                <li>{{ mykey }}
                    <ul>
                        {% if myvalue|character_list %}
                        {% for value in myvalue %}
                        <li>{{ value }}</li>
                        {% endfor %}
                        {% else %}
                        <li>{{ myvalue }}</li>
                        {% endif %}
                    </ul>
                </li>
                {% endfor %}
            </ol>
            <table>
                <tbody>
                <tr class="header_tr">
                    <td class="header_td" colspan="2">Заголовок 1</td>
                    <td class="header_td" colspan="2">Заголовок 2</td>
                    <td class="header_td" colspan="2">Заголовок 3</td>
                </tr>
                <tr>
                    <td rowspan="3">Характеристика 1</td>
                    <td>Свойство 1</td>
                    <td>Значение 1</td>
                    <td>77</td>
                    <td>Значение 1</td>
                    <td></td>
                </tr>
                <tr>
                    <td>Свойство 2</td>
                    <td>Значение 2</td>
                    <td>88</td>
                    <td>Значение 2</td>
                    <td></td>
                </tr>
                <tr>
                    <td>Свойство 3</td>
                    <td>Значение 3</td>
                    <td>99</td>
                    <td>Значение 3</td>
                    <td></td>
                </tr>
                <tr>
                    <td rowspan="3">Характеристика 2</td>
                    <td>Свойство 1</td>
                    <td>Значение 1</td>
                    <td></td>
                    <td>Значение 1</td>
                    <td>77</td>
                </tr>
                <tr>
                    <td>Свойство 2</td>
                    <td>Значение 2</td>
                    <td></td>
                    <td>Значение 2</td>
                    <td>88</td>
                </tr>
                <tr>
                    <td>Свойство 3</td>
                    <td>Значение 3</td>
                    <td></td>
                    <td>Значение 3</td>
                    <td>99</td>
                </tr>
                </tbody>
            </table>

            <h2>Подробное описание товара:</h2>
            <div id="full">
                <p>
                    {{ good.description|linebreaksbr }}
                </p>
            </div>
        </div>
    </div>
    {% block login %}
    <div class="modal fade" id="LoginPopup">
        <div class="modal-dialog">
            <div class="modal-content">
                <!-- header -->
                <div class="row justify-content-around">
                    <div class="col-md-8">
                        <h3 class="modal-title">Логин / Регистрация</h3>
                    </div>
                    <div class="col-md-2">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>
                </div>
                <br>
                <!-- body -->
                <div class="row justify-content-center">
                    <div class="col-md-8">
                        <form action="{% url 'auth:login' %}" method="post">
                            {% csrf_token %}
                            {{ login_form.as_p }}
                            <br>
                            <input class="btn btn-primary btn-block" type="submit" value="войти">
                            <br>
                        </form>
                    </div>
                    <div class="col-md-8">
                        <p class="text-center">
                            <a href="{% url 'auth:register' %}">Регистрация</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endblock %}
</div>
<footer class="footer fixed-bottom bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Сандал А. Я. 2018</p>
    </div>
</footer>
<script src="https://yastatic.net/jquery/3.1.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous">
</script>
<script>
var th = document.getElementById('thumbnails');

th.addEventListener('click', function(e) {
    var t = e.target,
    new_src = t.parentNode.href,
    large = document.getElementById('large'),
    large_href = document.getElementById('large_href'),
    cl = large.classList,
    lgwrap = document.getElementById('lg-wrap');
    lgwrap.style.backgroundImage = 'url(' +large.src + ')';
    if(cl) cl.add('hideme');

    window.setTimeout(function(){
        large.src = new_src;
        large_href.href = new_src;
        if(cl) cl.remove('hideme');
    }, 50);
    e.preventDefault();
}, false);





</script>
</body>
</html>

productsapp/templates/productsapp/inc_goods.html
{% for good in goods %}
<div class="col-lg-4 col-md-6 mb-4">
    <div class="card h-100">
        <a href="{% url 'products:detail' good_id=good.pk %}">
            <img class="card-img-top" src="/{{good.photos.all.0.src}}" alt="{{good.name}}">
        </a>
        <div class="card-body">
            <h4 class="card-title">
                <a href="{% url 'products:detail' good_id=good.pk %}">{{good.name}}</a>
            </h4>
            <h5>${{good.price}}</h5>
        </div>
    </div>
</div>
{% endfor %}

productsapp/templates/productsapp/slider.html
<div id='gallery' class='gallery'>
    <div id='lg-wrap' class='current-image-wrapper'>
        <a id='large_href' href='/{{good.photos.all.0.src}}' target='_blank'>
            <img id='large' data-idx='0' src='/{{good.photos.all.0.src}}' width='400'>
        </a>
    </div>
    <ul id='thumbnails' class='thumbnails'>
        {% for photo in good.photos.all %}
        <li>
            <a href='/{{photo.src}}'>
                <img data-idx='{{photo.pk}}' src='/{{photo.src}}'>
            </a>
        </li>
        {% endfor %}
    </ul>
</div>