authapp/urls.py
from django.conf.urls import url

import authapp.views as authapp

app_name = 'auth'
urlpatterns = [
    url(r'^login/$', authapp.login, name='login'),
    url(r'^logout/$', authapp.logout, name='logout'),
    url(r'^register/$', authapp.register, name='register'),
    url(r'^edit/$', authapp.edit, name='edit'),
]

basketapp/urls.py
from django.urls import path, re_path
from . import views
import basketapp.views as basketapp

app_name = 'basket'

urlpatterns = [
    path(r'^$', basketapp.basket, name='view'),
    path('add/<int:pk>/', basketapp.basket_add, name='add'),
    path('remove/<int:pk>/', basketapp.basket_remove, name='remove'),
]

contactsapp/urls.py
from django.urls import path, re_path
from . import views

app_name = 'contacts'
urlpatterns = [
    re_path(r'^$', views.main, name='main'),
]

geekbrains/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^$', include('mainapp.urls')),
    path('catalog/', include('productsapp.urls')),
    path('contact/', include('contactsapp.urls')),
    path(r'^basket/', include('basketapp.urls')),
    re_path(r'^auth/', include('authapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path, re_path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    re_path(r'^$', views.main),
]

productsapp/urls.py
from django.urls import path, re_path
from productsapp.views import (main, ProductDetailView, ProductCreateView, ProductDeleteView, ProductUpdateView,
                               ProductListView, CategoryUpdateView, CategoryCreateView, CategoryDeleteView)

app_name = 'products'

urlpatterns = [
    re_path(r'^$', ProductListView.as_view(), name='catalog'),
    path('<int:good_id>/', ProductDetailView.as_view(), name='detail'),
    path('create_prod/', ProductCreateView.as_view(), name='create_prod'),
    path('update_prod/<int:pk>/', ProductUpdateView.as_view(), name='update_prod'),
    path('delete_prod/<int:pk>/', ProductDeleteView.as_view(), name='delete_prod'),

    path('create_cat/', CategoryCreateView.as_view(), name='create_cat'),
    path('update_cat/<int:pk>/', CategoryUpdateView.as_view(), name='update_cat'),
    path('delete_cat/<int:pk>/', CategoryDeleteView.as_view(), name='delete_cat'),
]

mainapp/models.py
from django.db import models

# Create your models here.

mainapp/views.py
from django.shortcuts import render
from productsapp.models import ProductCategory, Good


def main(request):
    cats = ProductCategory.objects.all()
    goods = []
    for cat in cats:
        goods.append(Good.objects.filter(category=cat.pk)[0])
    # return render(request, 'mainapp/index.html', {'goods': goods})
    return render(request, 'mainapp/ext_index.html', {'goods': goods, 'categorys':cats})

mainapp/templates/mainapp/base_tmp.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Django Framework. Часть 1. Сандал А. Я.</title>
    {% block css %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css"
          integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{%  static '/css/shop-homepage.css' %}">
    {% endblock %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>

</head>

<body>
{% include 'mainapp/inc_nav.html' %}
<div class="container">
    {% block breadcrumb %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">Главная</a></li>
            <li class="breadcrumb-item"><a href="{% url 'products:catalog' %}">Каталог</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{good.name}}</li>
        </ol>
    </nav>
    {% endblock %}
    {% for message in messages %}
    <div class="alert {{ message.tags }} alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Закрыть">
            <span aria-hidden="true">&times;</span>
        </button>
        {{ message }}
    </div>
    {% endfor %}
    <div class="row">
        {% block left %}
        <div class="col-lg-3">
            <h2 class="my-4">Название магазина</h2>
            {% block categorys %}
            <div class="list-group">
                {% for cat in categorys %}
                <a class="list-group-item" href="{% url 'products:catalog' %}?cat={{cat.pk}}">{{ cat.name }}</a>
                {% endfor %}
            </div>
            {% endblock %}
            {% block basket %}
            <br>
            <div class='list-group'>
                <a href="{% url 'basket:view' %}" class='list-group-item list-group-item-success'>Корзина: {%if basket%}
                    {{ basket|length }} {% endif %} </a>
            </div>
            {% endblock %}
        </div>
        {% endblock %}
        <div class="col-lg-9">
            {% block carousel %}
            {% include 'mainapp/inc_carousel.html' %}
            {% endblock %}
            {% block content %}
            {% endblock %}
            {% block pagination%}
            {% endblock %}

        </div>
    </div>
    {% block login %}
    {% include 'mainapp/inc_login.html' %}
    {% endblock %}
</div>
<footer class="footer fixed-bottom bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Сандал А. Я. 2018</p>
    </div>
</footer>
{% block script %}
<script src="https://yastatic.net/jquery/3.1.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
{% endblock %}
</body>
</html>

mainapp/templates/mainapp/ext_index.html
{% extends 'mainapp/base_tmp.html' %}
{% block breadcrumb %}
{% endblock %}
{% block content %}
<h1>Самый лучший магазин</h1>
<div class="row">
{% for good in goods %}
<div class="col-lg-4 col-md-6 mb-4">
    <div class="card h-100">
        <a href="{% url 'products:detail' good_id=good.pk %}">
            <img class="card-img-top" src="/{{good.photos.all.0.src}}" alt="{{good.name}}"
                 width="300">
        </a>
        <div class="card-body">
            <h4 class="card-title">
                <a href="{% url 'products:detail' good_id=good.pk %}">{{good.name}}</a>
            </h4>
            <h5>${{good.price}}</h5>
            <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet
                numquam
                aspernatur!</p>
        </div>
        <div class="card-footer">
            <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
        </div>
    </div>
</div>
<!-- /.row -->
{% endfor %}
</div>
{% endblock %}

mainapp/templates/mainapp/inc_carousel.html
            <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner" role="listbox">
                    <div class="carousel-item active">
                        <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="First slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Second slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Third slide">
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>

mainapp/templates/mainapp/inc_login.html
    <div class="modal fade" id="LoginPopup">
        <div class="modal-dialog">
            <div class="modal-content">
                <!-- header -->
                <div class="row justify-content-around">
                    <div class="col-md-8">
                        <h3 class="modal-title">Логин / Регистрация</h3>
                    </div>
                    <div class="col-md-2">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>
                </div>
                <br>
                <!-- body -->
                <div class="row justify-content-center">
                    <div class="col-md-8">
                        <form action="{% url 'auth:login' %}" method="post">
                            {% csrf_token %}
                            {{ login_form.as_p }}
                            <br>
                            <input class="btn btn-primary btn-block" type="submit" value="войти">
                            <br>
                        </form>
                    </div>
                    <div class="col-md-8">
                        <p class="text-center">
                            <a href="{% url 'auth:register' %}">Регистрация</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>

mainapp/templates/mainapp/inc_nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="/">Главная</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'products:catalog' %}">Каталог</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'contacts:main' %}">Контакты</a>
                </li>
            </ul>
            <ul class="navbar-nav  ml-auto">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auth:edit' %}">{% if user.first_name > '' %}
                        {{ user.first_name }}{% else %}{{ user.username }}{% endif %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auth:logout' %}">Выйти</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="#" data-toggle="modal" data-target="#LoginPopup">Логин</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

mainapp/templates/mainapp/index.html
{% include "head.html" %}
<body>
<div class="outer">
    <header id="menu">
        {% include "menu.html" %}
    </header>
    <section id="main">
        <div class="mainWrap">
            <div class="contentLeft">
                <div class="mainMenu">
                    <a href="/">Главная</a>
                    <a href="/catalog">Каталог</a>
                    <a href="/contact">Контакты</a>
                </div>
            </div>
            <div class="contentRight">
                <div class="contentHeader">
                    <h1>Главная</h1>
                </div>
                <div class="catalog_goods">
                    {% for good in goods %}
                    <div class="catalog_good">
                        <a href="{% url 'products:detail' good_id=good.pk %}">
                            <img src="/{{good.photos.all.0.src}}" width="200" alt="{{good.name}}">
                        </a>
                        <div class="productName">
                            {{good.name}}
                        </div>
                        <div class="productPriceWrap">
                            <div class="actualPrice">
                                &euro; {{good.price}}
                            </div>
                        </div>
                        <a href="{% url 'products:detail' good_id=good.pk %}">Подробнее...</a>
                    </div>
                    {% endfor %}
                    <div class="shopDescr">
                        Описание магазина: Наш магазин самый лучший...
                    </div>
                </div>
            </div>
        </div>
    </section>
    <footer id="footer">
        {% include "footer.html" %}
    </footer>
</div>
</body>
</html>